--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Taylor-pm-pl/CmdScheduler
build-by-default: true
branches:
- master
projects:
  CmdScheduler:
    path: ""
    icon: icon.png
    includeDirs:
      vendor: vendor
...
